---
title: "CAVE Query: Proofread Cells"
format: 
    html:
        toc: true 
        code-fold: false
        code-links:
          - text: Download Quickstart Notebooks
            icon: file-code
            href: https://github.com/AllenInstitute/microns_tutorial/tree/main/tutorial_book/quickstart_notebooks
execute:
    eval: False
    warning: False
jupyter: python3
---

{{< include ../_annotation_tables/_archive_warning.qmd >}}

The **Connectome Annotation Versioning Engine (CAVE)** is a suite of tools developed at the Allen Institute and Seung Lab to manage large connectomics data.  

::: {.callout-important}
## Initial Setup
Before using any programmatic access to the data, [you first need to set up your CAVEclient token](em_py_01_caveclient_setup.html).
:::

## CAVEclient

Most programmatic access to the CAVE services occurs through CAVEclient, a Python client to access various types of data from the online services.

Full documentation for CAVEclient [is available here](http://caveclient.readthedocs.io).

To initialize a caveclient, we give it a **datastack**, which is a name that defines a particular combination of imagery, segmentation, and annotation database.
For the MICrONs public data, we use the datastack name `minnie65_public`.

In [1]:
import numpy as np
import pandas as pd

from caveclient import CAVEclient
datastack_name = 'minnie65_public'
client = CAVEclient(datastack_name)

# Show the description of the datastack
client.info.get_datastack_info()['description']

'This is the publicly released version of the minnie65 volume and segmentation. '

### Materialization versions

Data in CAVE is timestamped and periodically versioned - each (materialization) version corresponds to a specific timestamp. Individual versions are made publicly available. The Materialization client allows one to interact with the materialized annotation tables that were posted to the annotation service. These are called **queries** to the dataset, and available from `client.materialize`. For more, see the [CAVEclient Documentation](https://caveconnectome.github.io/CAVEclient/tutorials/materialization/).

Periodic updates are made to the public datastack, which will include updates to the available tables. Some cells will have different `pt_root_id` because they have undergone [proofreading](../proofreading.html). 

::: {.callout-tip}
For analysis consistency, is worth checking the version of the data you are using, and consider specifying the version with `client.version = your_version`

Read more about [setting the version of your analysis](/materialization-version.html#how-to-set-the-version-of-your-analysis)
:::

In [2]:
# see the available materialization versions
client.materialize.get_versions()

[1300, 117, 943, 1507, 1621, 1718]

And these are their associated timestamps (all timestamps are in UTC):

In [3]:
for version in client.materialize.get_versions():
    print(f"Version {version}: {client.materialize.get_timestamp(version)}")

Version 1300: 2025-01-13 10:10:01.286229+00:00
Version 117: 2021-06-11 08:10:00.215114+00:00
Version 943: 2024-01-22 08:10:01.497934+00:00
Version 1507: 2025-07-31 08:10:01.117494+00:00
Version 1621: 2025-11-25 08:10:01.094430+00:00
Version 1718: 2026-03-07 08:10:01.190228+00:00

In [5]:
# set materialization version, for consistency
client.version = 1718 # current public as of 3/7/2026

## Querying Proofread neurons

### Proofread neurons

Proofreading is necessary to obtain accurate reconstructions of a cell. In the MICrONS dataset, the general rule is that dendrites onto cells with a _single_ cell body are sufficiently proofread to trust synaptic connections onto a cell. Axons on the other hand require so much proofreading that only ~1800 cells have axons such that their outputs should be used for analysis.

{{< include /_annotation_tables/_proofreading_status_and_strategy.qmd >}}

Here we query and return the table as of version **1300**.

For the commands used for querying tables, see the [previous quickstart notebook on CAVE queries](02-cave-query-cell-types.html#querying-tables)

In [6]:
proof_all_df = client.materialize.query_table("proofreading_status_and_strategy", 
                                              desired_resolution=[1, 1, 1], 
                                              split_positions=True)

In [7]:
proof_all_df["strategy_axon"].value_counts()

strategy_axon
axon_partially_extended    1608
axon_fully_extended         547
axon_interareal             120
none                         41
Name: count, dtype: Int64

### Filtering Queries by proofreading status
We can filter our query to only return rows that match a condition by adding a filter to our query:

In [8]:
proof_axon_df = client.materialize.query_table("proofreading_status_and_strategy", 
                                               filter_in_dict={"strategy_axon": ["axon_partially_extended", "axon_fully_extended", "axon_interareal"]}, 
                                               desired_resolution=[1, 1, 1], 
                                               split_positions=True)
proof_axon_df.tail()

,id,created,superceded_id,valid,pt_position_x,pt_position_y,pt_position_z,valid_id,status_dendrite,status_axon,strategy_dendrite,strategy_axon,pt_supervoxel_id,pt_root_id
2270,5209,2026-03-06 20:48:04.965249+00:00,<NA>,True,729600,709568,875040,864691135858363694,True,True,dendrite_extended,axon_partially_extended,89876555228481414,864691135858363694
2271,5210,2026-03-06 20:48:04.986705+00:00,<NA>,True,688128,482432,812360,864691136111559352,True,True,dendrite_clean,axon_partially_extended,88391183537481077,864691136111559352
2272,5211,2026-03-06 20:48:05.008887+00:00,<NA>,True,770624,379072,823520,864691135920851376,True,True,dendrite_extended,axon_partially_extended,91272797422269509,864691135920851376
2273,5212,2026-03-06 20:48:05.024490+00:00,<NA>,True,740224,634880,903320,864691135480916422,True,True,dendrite_clean,axon_partially_extended,90225856462565231,864691135480916422
2274,5213,2026-03-06 20:48:05.042556+00:00,<NA>,True,683392,654592,887280,864691135886314096,True,True,dendrite_clean,axon_partially_extended,88256218753380966,864691135886314096

A more unified filter interface is available through a "table manager" interface.

Rather than passing a table name to the `query_table` function, `client.materialize.tables` has a subproperty for each table in the database that can be used to filter that table.

The general pattern for usage is

``` python
client.materialize.tables.{table_name}({filter options}).query({format and timestamp options})
```

where `{table_name}` is the name of the table you want to filter, `{filter options}` is a collection of arguments for filtering the query, and `{format and timestamp options}` are those parameters controlling the format and timestamp of the query.

::: {.callout-caution}
Use of this functionality will show a brief warning that the interface is experimental. This is because the interface is still being developed and may change in the near future in response to user feedback.
:::

With this, we can easily query all proofread cells with proofread axons:

In [9]:
proof_axon_df = client.materialize.tables.proofreading_status_and_strategy(strategy_axon=["axon_partially_extended", "axon_fully_extended", "axon_interareal"]).query(
    select_columns=['pt_root_id','status_axon','status_dendrite','strategy_axon','strategy_dendrite'],
)
proof_axon_df.tail()

,pt_supervoxel_id,pt_root_id,status_axon,status_dendrite,strategy_axon,strategy_dendrite
2270,89876555228481414,864691135858363694,True,True,axon_partially_extended,dendrite_extended
2271,88391183537481077,864691136111559352,True,True,axon_partially_extended,dendrite_clean
2272,91272797422269509,864691135920851376,True,True,axon_partially_extended,dendrite_extended
2273,90225856462565231,864691135480916422,True,True,axon_partially_extended,dendrite_clean
2274,88256218753380966,864691135886314096,True,True,axon_partially_extended,dendrite_clean

## Combining proofread cells and cell types

For analysis, often you are interested in neurons that are at the intersection of two or more groups. For example: **proofread cells** that are also **layer 2/3 pyramidal cells**. The general workflow for this type of analysis is to:

1. Query from one table, for example the `proofreading_status_and_strategy` table
2. Query from another table, for example the `aibs_metamodel_celltypes_v661`
3. Merge the two tables on the shared index, in this case `pt_root_id`

We covered [querying cell types in the previous quickstart notebook](02-cave-query-cell-types.html). Now lets put that together with the proofreading query:

In [10]:
# Query proofread cells with status_axon==True
proof_df = client.materialize.tables.proofreading_status_and_strategy(status_axon="t").query(
    select_columns=['pt_root_id','status_axon','status_dendrite','strategy_axon','strategy_dendrite'],
)

# Query cell types
cell_type_df = client.materialize.tables.aibs_metamodel_celltypes_v661().query(
    select_columns = {'nucleus_detection_v0': ['pt_root_id', 'id'],
                      'aibs_metamodel_celltypes_v661': ['classification_system','cell_type'],
                     },
)

::: {.callout-tip}
Note the 'select_columns' argument differs between the two tables. Thay is because the second table, `aibs_metamodel_celltypes_v661` is itself a reference on `nucleus_detection_v0`. That means the `id` column returned here is the same as the **nucleus id** of the cell. This is handy for referencing the same cell across materialization versions as the **nucleus id** does not change, whereas the `pt_root_id` will change with proofreading.
:::

Now we can merge the two tables together on the shared index! 

But it is worth checking if there are duplicates in either of the tables. How you handle duplicates will depend on your question, and the table you are using. Here we might see duplicates from multi-soma merges in the cell type table

In [11]:
cell_type_df.value_counts('pt_root_id')

pt_root_id
864691135698390426    346
0                     175
864691135566810455    102
864691136974041116     60
864691135455264362     43
                     ...
864691137199761729      1
864691137199763521      1
864691137199765313      1
864691137199772993      1
864691134273690220      1
Name: count, Length: 91489, dtype: int64

For analytical simplicity, we will drop any multi-soma objects. We will also rename the `id` column for clarity

In [12]:
# Drop duplicate pt_root_id and rename the nucleus_id
cell_type_df = (cell_type_df
                .drop_duplicates('pt_root_id', keep=False)
                .rename(columns={'id': 'nucleus_id'})
               )
                        
cell_type_df.head()

,pt_supervoxel_id,pt_root_id,nucleus_id,classification_system,cell_type
0,93606511657924288,864691136274724621,336365,excitatory_neuron,5P-IT
1,79385153184885329,864691135489403194,110648,excitatory_neuron,23P
2,79035988248401958,864691136147292311,112071,excitatory_neuron,23P
3,84529699506051734,864691135655940290,197927,nonneuron,oligo
4,83756261929388963,864691135809440972,198087,nonneuron,astrocyte

Now we can merge the two tables with `pandas.merge`, on index `pt_root_id`. We will keep the inner join of the two tables: cells that 1) are proofread, and 2) have a cell type

In [13]:
proof_cell_type_df = pd.merge(proof_df, cell_type_df, on='pt_root_id', how='inner')
proof_cell_type_df.tail()

,pt_supervoxel_id_x,pt_root_id,status_axon,status_dendrite,strategy_axon,strategy_dendrite,pt_supervoxel_id_y,nucleus_id,classification_system,cell_type
2187,89876555228481414,864691135858363694,True,True,axon_partially_extended,dendrite_extended,89876555228481414,301193,inhibitory_neuron,BC
2188,88391183537481077,864691136111559352,True,True,axon_partially_extended,dendrite_clean,88391183537481077,256304,excitatory_neuron,23P
2189,91272797422269509,864691135920851376,True,True,axon_partially_extended,dendrite_extended,91272797422269509,291125,inhibitory_neuron,NGC
2190,90225856462565231,864691135480916422,True,True,axon_partially_extended,dendrite_clean,90225856462565231,296750,excitatory_neuron,4P
2191,88256218753380966,864691135886314096,True,True,axon_partially_extended,dendrite_clean,88256218753380966,262886,excitatory_neuron,4P

And we have the list of all proofread cells, by their cell type!

We can do this same kind of query more simply by: querying the second table by BOTH the root ids of interest and the cell type of interest. If we wanted only the **proofread 23P cells**, we could do:

In [14]:
# Query the proofread 23P cells, and merge the proofreading status
proof_23p_df = (client.materialize.tables.aibs_metamodel_celltypes_v661(pt_root_id=proof_df.pt_root_id, cell_type='23P').query(
    select_columns = {'nucleus_detection_v0': ['pt_root_id', 'id'],
                      'aibs_metamodel_celltypes_v661': ['classification_system','cell_type'],
                     },  )
                .rename(columns={'id': 'nucleus_id'})
                .merge(proof_df, on='pt_root_id', how='inner')
               )

proof_23p_df.head()

,pt_supervoxel_id_x,pt_root_id,nucleus_id,classification_system,cell_type,pt_supervoxel_id_y,status_axon,status_dendrite,strategy_axon,strategy_dendrite
0,88884727087844075,864691135774053371,258375,excitatory_neuron,23P,88884727087844075,True,True,axon_partially_extended,dendrite_clean
1,88956195276658332,864691135257669039,258377,excitatory_neuron,23P,88956195276658332,True,True,axon_partially_extended,dendrite_clean
2,89378751472802282,864691135584646253,258403,excitatory_neuron,23P,89378751472802282,True,True,axon_fully_extended,dendrite_extended
3,88674101690450393,864691135763433270,258225,excitatory_neuron,23P,88674101690450393,True,True,axon_partially_extended,dendrite_clean
4,90150539848910271,864691134942468707,292833,excitatory_neuron,23P,90150539848910271,True,True,axon_partially_extended,dendrite_clean